name: Deploy Cloudflare Pages


on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'static/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: testproj
          directory: ./static
